### ISSUE TITLE
Problem with Wedo 2.0

### ISSUE THREAD

**Issue by heppg** [heppg/scratchClient#1]
In scratch forum,  at_nivelungen reported:

Now I'm using ScratchClient (http://heppg.de/ikg/wordpress/?page_id=6), which is Gerhard Hepp's work, with Wedo 2.0 on RPi3, but not working in my environment.

1. Followed 'Quick install procedure' in http://heppg.de/ikg/wordpress/?page_id=6, no problem on all of the steps.
2. Read http://www.heppg.de/ikg/administration/pi/scratchClient/doc/html/scratchClient.html#legowedo2_Adapter and installed 'bluepy' by

    $ sudo pip install bluepy

That went well.
3. Started Scratch 1.4 on my Rpi3 and typed the following command in the terminal to pair the RPi3 with Wedo 2.0:

    $ sudo python src/scratchClient.py -c config_wedo2_complete.xml

Then, displayed

    2017-03-16 23:34:44,276 - __main__ - INFO - Connected to Scratch !
    2017-03-16 23:34:44,278 - adapter.wedo2Adapter - WARNING - wedo2: Press 'connect'-Button on Hub

so pressed the button on Wedo 2.0 hub, then displayed

    2017-03-16 23:34:49,298 - adapter.wedo2Adapter - WARNING - wedo2: found device a0:e6:f8:fe:ac:40, LPF2 Smart Hub 2 I/O

but occured the following error during turning the LED between blue, red and green on the hub:

    2017-03-16 23:34:53,987 - adapter.wedo2Adapter - ERROR - notify_data, no service for port 6

The LED turned green at the end.
4. Without caring the error, tried to operator the motor on Wedo 2.0 by operating 'motor power 100' and 'motor on' on scratch software, but nothing happened.
Then, displayed the following errors:

    2017-03-17 00:31:03,768 - adapter.wedo2Adapter - ERROR - motion, data not parsed 04 02 00 00 00 40 03 2d 7a b4 42
    2017-03-17 00:31:14,216 - adapter.wedo2Adapter - ERROR - motion, data not parsed 04 02 00 00 80 40 03 2d 7a b4 42

The motor and the motion were connected to Port1 and Port2 on the hub, respectively.
I didn't modify 'config_wedo2_complete.xml'.
I downloaded scratchClient.tar.gz on March 6th, so it's the newest version.
The OS version of my RPi3 is as follows:

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID: Raspbian
    Description: Raspbian GNU/Linux 8.0 (jessie)
    Release: 8.0
    Codename: jessie

**Comment by heppg** [comment]
User did use motor blocks (not applicable) instead of the correct variable names.
Closed, works as designed.

**Comment by eltechno** [comment]
hi! i know this issues is closed but i just want to know what variables or how to use that variables to move the motor ? 
any examplet where i can see how to do that ?
