### ISSUE TITLE
Delay and events

### ISSUE THREAD

**Issue by unmanagedtn** [heppg/scratchClient#2]
There is a huge delay when using the mpr121...  between touch and events registering...

I am trying to make an interactive touch game but the delay between touch and register of events is delayed by a few second.. cant get it increment the score on touch... and 
I was also trying to get this to work remotely with the windows client and could not load extension.

Any input would be great as I must be doing something wrong...

<a href="https://ibb.co/HCfWYfv"><img src="https://i.ibb.co/m0VLtVs/scratch.jpg" alt="scratch" border="0"></a>

**Comment by heppg** [comment]
Difficult to measure time from start trigger at touch input till scratch2 shows event. 

Approach taken used an automated stimulus, a LED to make stimulus visible and a video to capture time delay between stimulus and scratch2 reaction. In detail:

- edited config_touch_mpr121.xml and reduced polling time from 0.1 to 0.05
- attached a microcontroller output to mpr121 input, switching an additional cap and so simulating manual touch, automatic repeating this at a rate of 3 sec. The interrupt led on adafruit MPR121 breakout blinks at this rate.
- microcontroller also switches a LED which was placed close to monitor.
- scratch2 on raspberry pi
- used a small scratch program to display event. mpr121_evt_01 to "say text"
- created a video showing LED and scratch reaction. 25 frames per sec. 40 ms resolution.
- with a video cut software, took time LED switched on and scratch reacted by display text.

Time is prox 0,26 sec  which is not fast, but acceptable.
Where are the delays:
mpr121 is cyclic polling its inputs.
scratchCllient is polling the state of the device
takes some processing time from event input till websocket output towards javascript adapter
scratch2 needs some tome to process event.
