### ISSUE TITLE
scratchx does not load exten

### ISSUE THREAD

**Issue by unmanagedtn** [heppg/scratchClient#3]
http://192.168.1.23:8080/scratchx/documentation/scratchClient.html

following above instructions for scratch client does not load correctly see image,,,,

<a href="https://ibb.co/yQq7BHY"><img src="https://i.ibb.co/XCtMkc3/scratchx.jpg" alt="scratchx" border="0"></a>

**Comment by heppg** [comment]
Executed the scratchX startup procedure here.
Step 1: load extension block from  https://megjlow.github.io/extensionloader.js
This is working as expected. 
Step 2: loading scratchClient extension with the block from Step1, use http://192.168.2.115:8080/scratchx/js/extension.js The ip address is local here, adjust to your settings.
This is working here. There is a flaw that the scratchClient blocks do not load in production mode (each event a single block), but in 'workshop' mode (single event block which allows to select the event).

If not working on your machine, then download latest scratchClient from http://heppg.de/ikg/wordpress/?page_id=6. There was a bugfix in 2019-02-02 regarding the scratch2 connection.

If not working on your machine, use url http://192.168.2.115:8080/scratchx/js/extension.js (adjust to your pi setting) in a browser. You should get some javascript code displayed (of course not running, but this validates that network connection is fine).

Summary: works here. No bug.
